title: Code Club Missions

remote_theme: just-the-docs/just-the-docs

url: "https://aliblol.github.io"
baseurl: "/code-club-missions"

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default

search_enabled: true
